export const productsConstants = {
    CREATE_REQUEST: 'CREATE_REQUEST',
    SUCCESS_REQUEST: 'SUCCESS_REQUEST',
    CREATE_REQUEST_PRODUCT: 'CREATE_PRODUCT_REQUEST',
    SUCCESS_REQUEST_PRODUCT: 'SUCCESS_PRODUCT_REQUEST'
};