export const productsConstants = {
    CREATE_REQUEST: 'CREATE_REQUEST',
    SUCCESS_REQUEST: 'SUCCESS_REQUEST',

    CREATE_REQUEST_PRODUCT: 'CREATE_PRODUCT_REQUEST',
    SUCCESS_REQUEST_PRODUCT: 'SUCCESS_PRODUCT_REQUEST',

    REQUEST_DELETE_PRODUCT: 'REQUEST_DELETE_PRODUCT',
    SUCCESS_DELETE_PRODUCT: 'SUCCESS_DELETE_PRODUCT',
    FAILURE_DELETE_PRODUCT: 'FAILURE_DELETE_PRODUCT',

    REQUEST_UPDATE_PRODUCT: 'REQUEST_UPDATE_PRODUCT',
    SUCCESS_UPDATE_PRODUCT: 'SUCCESS_UPDATE_PRODUCT',
};